### GET auth jwt

GET http://localhost:8080/api/auth/jwt/6564e1d402b5db9730b5ccf7
Content-Type: application/xml
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWIxNDhkOTkxNWM3MWE4MGRlMmI3YTciLCJmaXJzdE5hbWUiOiJxcSIsImxhc3ROYW1lIjoicXEiLCJlbWFpbCI6ImZpbnF1aW5AZ21haWwuY29tIiwidXNlciI6InFxIiwiYWdlIjoyMiwicGFzc3dvcmQiOiIkMmIkMTAkbGhyRnU3R0VZTWdqQkRtUVhDdzF1LlZlYUJRdU1kT0lXZmxwdVVuckkwZkVVQ28ydVRETnkiLCJpc0dpdEh1YiI6ZmFsc2UsInJvbCI6IlVTRVIiLCJjYXJ0IjoiNjViMTQ4ZDk5MTVjNzFhODBkZTJiN2E1IiwiaWF0IjoxNzA2MTQxNTIyfQ.tduAgjhy7PRyn0tYyoXZNYI-oRzQzjuW3PgfQUX2X7c
