// [x]
### GET Listar todos los productos
GET  http://localhost:8080/api/products


// [x]
### GET Listar producto por ID
GET  http://localhost:8080/api/products/6556a4c8488c5c5ef331c692

// [x]
### GET Seleccionarlimite
GET  http://localhost:8080/api/products?limit=3


// [x]
### GET Seleccionar ordenar
GET  http://localhost:8080/api/products?sort=ascd

// [x]
### GET Seleccionar page
GET  http://localhost:8080/api/products?page=2


// [x]
### GET Seleccionar limit,sort(ascd,desc,page
GET http://localhost:8080/api/products?limit=3&page=2&sort=desc

// [x]
### POST agrega productos
POST http://localhost:8080/api/products
Content-Type: application/json

{
		"title": "Sandíass",
		"description": "Sandía dulce y refrescante.",
		"code": "A1a2ee4",
		"price": 3.99,
		"status": true,
		"thumbnails": "/img/imagen_sandia.webp",
		"category": "Frutas",
		"stock": 50
	}

// [x]
### PUT actualiza los productos
PUT http://localhost:8080/api/products/657623b5af83a13481b59522
Content-Type: application/json

{
"code": "A1323",
"stock":11122
}

// [x]
### DELETE Elimima el producto
DELETE  http://localhost:8080/api/products/657623b5af83a13481b59522



